### ISSUE TITLE
Sort academic positions by importance

### ISSUE THREAD

**Issue by ericras** [unl/UNL_Directory#121]
If a faculty member has multiple appointments sort them by importance.

For example, if they are "Courtesy Assoc Professor" and "Assoc Professor" make sure that "Assoc Professor" is displayed first.

**Comment by ericras** [comment]
Other than just hardcoding strings, could look at the ZFTE value in UNL_APPOINTMENTS an weight 100.00 above null.  Or DIRECTORY_ORDER (if that is being used)

**Comment by ericras** [comment]
DIRECTORY_ORDER is being used and is available.  "01" is most significant value.

**Comment by jsturek** [comment]
Completed with https://github.com/unl/UNL_Directory/pull/122/commits/8f8edda24e2f1fbadf1c6e7ca504fe1a730241cf
