### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by ericras** [unl/UNL_Directory#152]
Splunk search: PHP Fatal error host=ucommsrv3.unl.edu

Happens with various searches: Dylan, Ren, Cassandra
 
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /var/www/html/directory/src/UNL/Peoplefinder/Driver/OracleDB.php:255\nStack trace:\n#0 /var/www/html/directory/src/UNL/Peoplefinder/Driver/OracleDB.php(255): iterator_to_array(NULL)\n#1 /var/www/html/directory/src/UNL/Peoplefinder/Driver/LDAP.php(478): UNL_Peoplefinder_Driver_OracleDB->fixLDAPEntries(Array)\n#2 /var/www/html/directory/src/UNL/Peoplefinder/Driver/LDAP.php(248): UNL_Peoplefinder_Driver_LDAP::normalizeLdapEntries(Array)\n#3 /var/www/html/directory/src/UNL/Peoplefinder/Driver/LDAP.php(393): UNL_Peoplefinder_Driver_LDAP->query('(&(&(|(mail=Dyl...', Array)\n#4 /var/www/html/directory/src/UNL/Peoplefinder.php(268): UNL_Peoplefinder_Driver_LDAP->getLikeMatches('Dylan', NULL, Object(UNL_Peoplefinder_SearchResults))\n#5 /var/www/html/directory/src/UNL/Peoplefinder/SearchController.php(104): UNL_Peoplefinder->__call('getLikeMatches', Array)\n#6 /var/www/html/directory/src/UNL/Peoplefinder/SearchContr in /var/www/html/directory/src/UNL/Peoplefinder/Driver/OracleDB.php on line 255

**Comment by jsturek** [comment]
Fix with https://github.com/unl/UNL_Directory/issues/152
