### ISSUE TITLE
Prevent 'duplicate' departments from displaying in directory

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_Directory#49]
This really boils down to two tasks.

- [x] Prevent departments with the `suppressed` flag from displaying in search results
- [x] ~~Define a new relationship between departments which would tell directory that an employee's org unit (department) is a duplicate and another one should be shown instead. Duplicate departments exist for administration purposes and can be confusing to end users.~~ see https://github.com/unl/UNL_Directory/issues/49#issuecomment-226289329

While we can easily prevent `suppressed` departments from displaying in search, an employee might still belong to a `suppressed` department. If an employee belongs to a `suppressed` department, their record in directory will currently display and link to that `suppressed` department because we have no way of knowing what department to display instead. This will require some extra thought and care to ensure that we still provide appropriate details.

---

Original email from Dave:
The first link(s) in each is the department we have known and can edit, the others are separate listings that ideally we would like to merge into the first.

CEHS
  https://directory.unl.edu/departments/144
  https://directory.unl.edu/departments/143
  https://directory.unl.edu/departments/207
  
TMFD
  https://directory.unl.edu/departments/147
  https://directory.unl.edu/departments/210

CYAF
  https://directory.unl.edu/departments/145
  https://directory.unl.edu/departments/208

NHS
  https://directory.unl.edu/departments/146
  https://directory.unl.edu/departments/209

**Comment by mfairchild365** [comment]
@kabel do you have any thoughts on this, do you think it is accurate?

**Comment by saltybeagle** [comment]
An alternative could be to ask these departments to add a courtesy/unpaid appointment in the org unit under which they'd like to be publicly represented, then add the "NL" (not-listed) flag to the appointment line they want hidden in the directory. If all employees and appointments within an org unit are hidden, suppress it as usual and remove any yellow-pages listings to prevent it from showing up.

This may not solve the roll-up org entries which are empty, but could resolve the issue with an employee not showing up alongside expected coworkers.

**Comment by mfairchild365** [comment]
@saltybeagle that is great advice and probably better than duplicated a similar workflow in directory itself, I will pass that along. I think we still need to address the first issue where 'suppressed' departments are still showing up in search.
