### ISSUE TITLE
Orgunit personnel subtrees can be slow due to DM requests

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_Directory#55]
The endpoint `departments/{org number}/personnelsubtree?format=xml` can be slow due to requests to digital measures. The resource returns a list of person records, each of which will request information from Digital Measures. If the digital measures info is not cached, each person record can take about a second to load. So if there are 50 people in the list, it can take 50 seconds for the request to finish. There are a few potential ways to improve this:

1. leverage a DM api to get information about all users in one request
2. cache DM data asynchronously and return the last cached data in the meantime
3. Increase the TTL for the cache (will mitigate the problem but not solve it)

**Comment by mfairchild365** [comment]
@kabel do you know if anyone is using the DM data in that endpoint, was it added to that endpoint for a specific reason? It might be best to remove the DM output from that endpoint altogether.

If it is required, it would probably best to do option 1 or 2 (or a combination of both!).

**Comment by mfairchild365** [comment]
We are going with option 4. ;)

DM has a `/User` endpoint which lists all users in the system. Using this endpoint, we should be able to create a CRON job which caches all DM data. This way a request to directory would never have to wait on DM, and would ONLY ever used cached data.

**Comment by tlemburg** [comment]
I have made a pull request that fixes this: https://github.com/unl/UNL_Directory/pull/56
