### ISSUE TITLE
Positions/Titles for central employees now gone

### ISSUE THREAD

**Issue by kabel** [unl/UNL_Directory#84]
The move to oracle for position information seems to have shaken things up a bit. This side-effect results in employees from central, that are in LDAP, appearing without any position/title information.  Example: https://directory.unl.edu/people/hbounds2 used to show title "President" from a position in https://directory.unl.edu/departments/50000094

**Comment by ericras** [comment]
https://github.com/unl/UNL_Directory/pull/106
